### ISSUE TITLE
Using Gitlab Env Variables

### ISSUE THREAD

**Issue by akowi-sknobloch** [esatterwhite/semantic-release-docker#42]
Hi,

Im trying to update my projects build scripts to use this plugin for the docker release.
My Projects are on a self hosted internal Gitlab and the images should be deployed to the Gitlab Docker Registry of the given Project.

At the moment i use semantic-release to change the version in the `package.json` followed by straight Docker commands in my `.gitlab-yi.yml`
My Deploy stage looks like this:
```yaml
deploy:
  image: docker:stable
  stage: deploy
  services:
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build --cache-from $CI_REGISTRY_IMAGE:latest -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE:latest
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
```
This works but has the disadvantage, that the images do not get tagged with the semantic-release version.

Now here is my updated `.gitlab-ci.yml` using `semantic-release-docker`:
```yaml
default:
  image: node:18-alpine

release-increment:
  services:
    - docker:dind
  stage: release-increment
  before_script:
    - apk add docker git
  script:
    - DOCKER_REGISTRY_USER=$CI_REGISTRY_USER; DOCKER_REGISTRY_PASSWORD=$CI_REGISTRY_PASSWORD; npm run semantic-release
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .npm/
```

And here is my `release.config.js`:
```js
module.exports = {
  branches: ['main'],
  plugins: [
    '@semantic-release/commit-analyzer',
    '@semantic-release/release-notes-generator',
    '@semantic-release/gitlab',
    [
      '@semantic-release/npm',
      {
        npmPublish: false,
      },
    ],
    [
      '@semantic-release/git',
      {
        assets: ['package.json'],
        message:
          'chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}',
      },
    ],
    [
      '@codedependant/semantic-release-docker',
      {
        dockerTags: ['latest', '{{version}}'],
        dockerRegistry: '{{env.CI_REGISTRY}}',
        dockerImage: '{{env.CI_REGISTRY_IMAGE}}',
      },
    ],
  ],
};
```

The build fails with the error: 
```
'ERROR: invalid tag "{{env.CI_REGISTRY}}/{{env.CI_REGISTRY_IMAGE}}:070ac7d3bcc70fc2a293": invalid reference format'
```

Seems like the I cannot access the Env Variables.
Hopefully someone can help me with this :)

**Comment by esatterwhite** [comment]
The thing you want to do is just reference arbitrary environment variables?

**Comment by esatterwhite** [comment]
or that you want dockerRegistry and dockerImage to be templated? That sounds like more the problem? they just aren't templated.

**Comment by akowi-sknobloch** [comment]
> or that you want dockerRegistry and dockerImage to be templated?

Yes that's pretty much what i want.
Gitlab provides a Docker Registry with its own URL for every Project.
The environment variables get set automatically by  Gitlabs CI Runner.

**Comment by goestav** [comment]
I ran into the same issue on GitLab CI/CD
I'm using a js release config file as workaround:
```js
{
    [
        '@codedependant/semantic-release-docker',
        {
            dockerProject: process.env.CI_PROJECT_NAMESPACE,
            dockerRegistry: process.env.CI_REGISTRY
        }
    ]
}
```

**Comment by esatterwhite** [comment]
Yeah, that's totally valid too. For a simple use case like this, that is why the js config is file is supported

**Comment by esatterwhite** [comment]
@akowi-sknobloch if you are using a js config you don't really need it to be templates. Just use the env vara

```javascript
    [
      '@codedependant/semantic-release-docker',
      {
        dockerTags: ['latest', '{{version}}'],
        dockerRegistry: process.env.CI_REGISTRY,
        dockerImage: process.env.CI_REGISTRY_IMAGE,
      },
    ]
```

**Comment by akowi-sknobloch** [comment]
Great using the process.env works like a charm.
Now my Pipeline produces a nice Docker Image tagged with my Semantic Release version just how i want it.
Thank you both!

**Comment by ticapix** [comment]
That's an awesome feature !

It give me generic `release.config.mjs` I can copy/paste in my Gitlab projects.

As a reference for the next readers:

```javascript
/**
 * @type {import('semantic-release').GlobalConfig}
 */
export default {
...
 [
      "@codedependant/semantic-release-docker",
      {
        dockerRegistry: process.env.CI_REGISTRY,
        dockerProject: process.env.CI_PROJECT_NAMESPACE,
        dockerImage: process.env.CI_PROJECT_NAME,
        dockerCacheFrom: process.env.CI_REGISTRY + '/' + process.env.CI_PROJECT_PATH + ':latest',
        dockerLogin: false,
        dockerArgs: {
          VERSION: "{{next.version}}"
        }
      }
    ]
  ]
};
```

and in the `.gitlab-ci.yml`

```yaml
build:
  stage: build
  image: docker:29-cli
  services:
    - name: docker:dind
  before_script:
    - if [ "$GITLAB_CI" == true ]; then echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin; fi
    - apk add git openssh-client nodejs npm
    - npm install
  script:
    - npx semantic-release
```

with `package.json`

```json
{
  "devDependencies": {
    "@codedependant/semantic-release-docker": "^5.1.1",
    "@semantic-release/changelog": "^6.0.3",
    "@semantic-release/exec": "^7.1.0",
    "@semantic-release/gitlab": "^13.2.9",
    "conventional-changelog-conventionalcommits": "^9.1.0"
  }
}
````
